tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-drivers"
tap "homebrew/services"
brew "neovim", args: ["HEAD"]
cask "iterm2"
cask "brave-browser"
brew "node"
brew "fnm"
brew "fzf"
brew "wget"
brew "ranger"
cask "rectangle"
brew "yq"
brew "jq"
brew "zsh-completions"
brew "pyenv"
brew "bat"
