#!/bin/sh
INCLUDE=""
while getopts "i" options; do
  case "${options}" in
    i)
      INCLUDE="yes"
      ;;
  esac
done

script='
def pad($len): tostring | .[0:$len-5] | . + " " * ($len-length) ;

def makeLineInfo: ""
    + ( "con_id=\(.id)"
    + if .window != null       then "; id=\(.window)" else "" end
    + if (.marks | length) > 0 then "; marks=( "+(.marks|@sh)+" )" else "" end
    )
;'
if [ "$INCLUDE" = "" ]; then
  script=$script'
  def makeLine($y):
      .focused as $is_focused
      | ( $y +
          if .window != null        then "- win: (\(.window_properties.class)) \(.name)"
          elif .type == "workspace" then "\(.name):"
          elif .type == "con"       then "container: \(.layout)"
          elif .type == "output"    then "output:   \(.name)"
          else "Well This is unexpected  \(.|tostring)" end
      | pad(100) ) + makeLineInfo
      | if $is_focused then "--> " + .[4:] else . end
  ;'
else
  script=$script'
  def makeLine($y):
      .focused as $is_focused
      | ( $y +
          if .window != null        then "- win: (\(.window_properties.class)) \(.name)"
          elif .type == "workspace" then "\(.name):"
          elif .type == "con"       then "container: \(.layout)"
          elif .type == "output"    then "output:   \(.name)"
          else "Well This is unexpected  \(.|tostring)" end
      | pad(100) ) + makeLineInfo
      | if $is_focused then "" else . end
  ;'
fi
script=$script'
def i3_descend_nodes($y): makeLine($y), (
    if .type == "output"
    then .nodes[] | select(.name == "content")
    else .nodes[]
    end | i3_descend_nodes($y + "  ") )
;

.nodes[]
| [ select(.name != "__i3") ]
| if length > 1 then .[] else
    .[] | .nodes[] | select(.name == "content") | .nodes[]
end
| i3_descend_nodes("") '

i3-msg -t get_tree | jq -r "$script"
