#!/usr/bin/zsh
LANG="python3"
CLICOLOR_FORCE=1

prob=$(leetcode list | fzf --ansi | sed 's/.*\[\([^]]*\)\].*/\1/')
leetcode pick $prob | less

echo "Enter language for solution (default $LANG):"
read LANG_INPUT
if [[ ! -z "$LANG_INPUT" ]];
then
  LANG=$LANG_INPUT
fi
leetcode edit $(( $prob )) --lang $LANG

